[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=[
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/",
    "quabi/=lib/quabi/src/",
    "@chimera/=lib/chimera/src/",
    "murky/=lib/murky/src/",
    "solady/=lib/solady/src/",

    "v3-core/=lib/v3-core/contracts/",
    "v3-periphery/=lib/v3-periphery/contracts/",
    "v3-core-0_8/=lib/v3-core-0_8/contracts/",
    "v3-periphery-0_8/=lib/v3-periphery-0_8/contracts/",

    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/",


    # required for Uniswap Periphery/Core compatibility
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
